### ISSUE TITLE
추가적인 코드, 커밋, 컨벤션 설정 및 이슈 템플릿 추가

### ISSUE THREAD

**Issue by Tolerblanc** [42Seoul-LastDance/ft_transcendence#6]
## 요약
- 회의 내용을 기반으로, 각종 컨벤션을 파일로 만들어 vscode 플러그인을 통한 자동화 
- `.vscode`, `.github`, `.eslint.js`, `.prettierrc` 활용

## 내용
- `.vscode/setting.json` 파일을 통해 포맷팅 플러그인이나 기타 설정 공유
- `.eslint.js`, `.prettierrc` 파일을 통해 indent 폭, 줄바꿈 폭, 후행 컴마 여부 등 플러그인을 통해 적용할 코드 형식 지정
- `.github/`에 버그 이슈 템플릿과 같이 여러 이슈 타입에 대한 템플릿 추가
- `.github/.gitmessage`로 커밋 템플릿 적용
- Issue, PR, Projects, Branch 사용법 숙지

## 참고자료
- Notion -> Common Rules
- [eslint를 사용할 때 prettier의 설정](https://heewon26.tistory.com/262)
- [perttier와 eslint를 구분하여 사용하자](https://velog.io/@yrnana/prettier%EC%99%80-eslint%EB%A5%BC-%EA%B5%AC%EB%B6%84%ED%95%B4%EC%84%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EC%9E%90)
- [prettier docs](https://prettier.io/docs/en/configuration.html#editorconfig)

**Comment by ebang091** [comment]
너무 좋습니다~~
풀리퀘 만들때 이 이슈 번호 (#'6) 붙여서 커밋하면 넘 좋을 거 같아요!
